#!/bin/bash
set -e

##
# SSH to an ECS cluster
# Open an SSH connection to a host instance within an ECS cluster.
##

USAGE="Open an SSH connection to a host instance within an ECS cluster.

Usage:
  ssh-to-cluster <name> [...]

Parameters:
  <name>    Name of the ECS cluster.
  [...]     Additional parameters will be passed to the SSH command.

Example usage:
  ssh-to-cluster default -N -L 3306:path.to.mysql.rds.amazonaws.com:3306
"

if [ -z $1 ]
then
	echo "$USAGE"
	exit 1
fi

CLUSTER=$1

export AWS_DEFAULT_OUTPUT="text"

CONTAINER_INSTANCE=$(aws ecs list-container-instances --cluster $CLUSTER --query 'containerInstanceArns[0]')
EC2_INSTANCE=$(aws ecs describe-container-instances --cluster $CLUSTER --container-instance $CONTAINER_INSTANCE --query 'containerInstances[0].ec2InstanceId')
EC2_HOSTNAME=$(aws ec2 describe-instances --instance $EC2_INSTANCE --query 'Reservations[0].Instances[0].PublicIpAddress')

echo "Connecting to $EC2_INSTANCE at $EC2_HOSTNAME"
exec ssh ec2-user@$EC2_HOSTNAME "${@:2}"
