#!/bin/bash
set -e

##
# SSH to a service host
# Open an SSH connection to the host instance of a running ECS service.
##

USAGE="Open an SSH connection to the host instance of a running ECS service.

Usage:
  ssh-to-service-host <cluster> <service> [...]

Parameters:
  <cluster>    Name of the ECS cluster.
  <service>    Name of the service.
  [...]        Additional parameters will be passed to the SSH command.

Example usage:
  ssh-to-service-host default my-service
"

if [ -z $1 ] || [ -z $2 ]
then
	echo "$USAGE"
	exit 1
fi

CLUSTER=$1
SERVICE=$2

export AWS_DEFAULT_OUTPUT="text"

TASK_ARN=$(aws ecs list-tasks --cluster $CLUSTER --service-name $SERVICE --query 'taskArns[0]')
CONTAINER_INSTANCE=$(aws ecs describe-tasks --cluster $CLUSTER --tasks $TASK_ARN --query 'tasks[0].containerInstanceArn')
EC2_INSTANCE=$(aws ecs describe-container-instances --cluster $CLUSTER --container-instance $CONTAINER_INSTANCE --query 'containerInstances[0].ec2InstanceId')
EC2_HOSTNAME=$(aws ec2 describe-instances --instance $EC2_INSTANCE --query 'Reservations[0].Instances[0].PublicIpAddress')

echo "Connecting to $EC2_INSTANCE at $EC2_HOSTNAME"
exec ssh ec2-user@$EC2_HOSTNAME "${@:3}"
